### ISSUE TITLE
Save Projects

### ISSUE THREAD

**Issue by Fethi-Hamdani** [deven98/MetaFlutter#8]
do you guys agree to adding a database for saving layouts, it is really frustrating losing everything and you have to go all over from zero

**Comment by d3xvn** [comment]
Absolutely! I'm trying a JSON based approach by serialising the widget classes and I hope to complete it by this week. We need to add saving layouts before we can take the app out of beta. Thanks for the suggestion! 

(P.S: There is a dev branch with a try to serialise the classes but I'm now trying to use json_serialiser to serialise classes instead.)

**Comment by yanir-edri** [comment]
I'm now working on deserializing the models from text code, once I'm done we'll have export/import functionality which can work with simply saving it as text.
You could also paste some text of UI and try it out

**Comment by d3xvn** [comment]
@yanir-edri That sounds great, similar to what I'm doing on the dev branch but I'm looking for a slightly more scalable solution than mine. If you're confident with your solution, I can revert the dev branch to match the master branch and push yours on it directly.

**Comment by yanir-edri** [comment]
It's going pretty well, I just can't figure out how to parse the colors because they're not inside an enum, and I can't expect the pasted code to contain a color we have in our list.
Any suggestions?
I'll commit what I did today.
Edit: [Here](https://github.com/yanir-edri/MetaFlutter/blob/master/lib/utils/code_utils.dart) is the new file.

**Comment by d3xvn** [comment]
Yeah the colors are a real problem because some are MaterialColors and some are Swatches for which we need to use a specific value like "[500]". So even toString() isn't doing the job well. I'll review your file and let you know. Since you've tested it a bit, is it working for everything except colors?

**Comment by yanir-edri** [comment]
I hope I'll have some time to finish and test it by tommorow

**Comment by yanir-edri** [comment]
[This](https://github.com/yanir-edri/MetaFlutter/blob/master/lib/utils/code_utils.dart) can currently parse code that doesn't contain widgets with multiple children, I'll add it tomorrow. Meanwhile, check out [this](https://github.com/yanir-edri/MetaFlutter/blob/master/lib/pages/widget_structure_screen.dart) - change ```test``` to true and see it in action! :)
I also wanted to raise a question: Can a widget constructor contain multiple un-named parameters? (an example for an unnamed parameter is the text parameter in the Text widget  -it is constructed with Text("..."), so the text parameter is unnamed).
